### PR TITLE
Finalize Backend (improved)

### PR DESCRIPTION
**Pull request by benwaffle**
Has everything in #3, and writes comments too

### CODE REVIEW

**Comment by benwaffle** [comment]
pls

**Comment by btkostner** [comment]
I added a `Dockerfile` so you can test out the building as well.

I currently get this output:
```
btkostner@Caprica:~/Projects/Web/vala-docs/doc-gen$ docker run -v $(pwd):/valadoc valadoc
[ -d girs ] && git -C girs pull || git clone https://github.com/nemequ/vala-girs.git girs
Already up-to-date.
rm -f -r docs
G_MESSAGES_DEBUG=all valadoc \
	-o docs \
	--importdir girs/gir-1.0 \
	--import GLib-2.0 \
	--import GObject-2.0 \
	--girdir girs/gir-1.0 \
	--vapidir girs/vala/vapi \
	--doclet . \
	--driver 0.34 \
	--deps
glib-2.0.vapi: char.tolower: @link: warning: `tolower' does not exist
glib-2.0.vapi: char.tolower: @param: warning: Unknown parameter `c'
glib-2.0.vapi: char.toupper: @link: warning: `toupper' does not exist
glib-2.0.vapi: char.toupper: @param: warning: Unknown parameter `c'
...
gobject-2.0.vapi: GLib.Value.dup_variant: @link: warning: `g_variant_unref' does not exist
gobject-2.0.vapi: GLib.Value.register_transform_func: @param: warning: Unknown parameter `transform_func'
gobject-2.0.vapi: GLib.Value.strdup_contents: @param: warning: Unknown parameter `value'
gobject-2.0.vapi: GLib.Value.dup_boxed: @link: warning: `g_boxed_free' does not exist
valadoc: symbol lookup error: /valadoc/libdoclet.so: undefined symbol: xmlNewTextWriterFilename
Makefile:10: recipe for target 'generate-xml' failed
make: *** [generate-xml] Error 127
```

**Comment by benwaffle** [comment]
I fixed the build inside docker. The problem was the order of the arguments passed to gcc

**Review by btkostner — APPROVED** [review]
Seems good to me

**Review by lewisgoddard — APPROVED** [review]

**Pull request merged**
