### PR TITLE
Finalise backend.

### PR DESCRIPTION
**Pull request by MarcusWichelmann**
Finish the backend to generate xml files that contain (hopefully) all needed information.

---
### Todo
- [x] Comments (See Ben's branch)
- [x] Method Parameters
- [x] Type Parameters (Needs testing!)
- [x] Exclude generated files for a reviewable diff

### CODE REVIEW

**Comment by benwaffle** [comment]
should constructors be `<constructor>` and not `<method>`?

**Comment by lewisgoddard** [comment]
Should we file the lack of comments and method parameters/arguments as separate issues and merge this, seeing as it's significantly far ahead of master, we don't want too much separation. With this, I can start work on the frontend.

**Comment by benwaffle** [comment]
the comments are essential to valadoc, we're not writing a symbol browser

**Comment by lewisgoddard** [comment]
Sure, but I can write a frontend with placeholders with this, I'm not sure that anything written against master right now would work once this branch was merged.

**Comment by lewisgoddard** [comment]
I don't suppose anyone here fancies finishing the work on comments & method parameters/arguments?

**Comment by MarcusWichelmann** [comment]
Is this branch still blocking the development of the new vala-docs.org webpage? What are you current plans to do with it, if it when it's finished (hopefully... sometimes...)?
The last time I looked into it I didn't understand how to use the libraries to get these information like method arguments and comments... Maybe somebody who knows the vala-core-libraries better is able to figure out how to add the last missing features.
But the biggest part of the work on the generator is already done.

**Comment by lewisgoddard** [comment]
For eustasy/vala-docs.org yes, for Valadoc/valadoc-org no.

Ultimately, the current generator is seriously flawed, and needs replacing. I'd like to see this adopted as the official Vala Docs site, and to start by replicating all the current functionality here.

**Comment by benwaffle** [comment]
I figured out how to get the comments some time ago

**Comment by MarcusWichelmann** [comment]
I'll look into it again now. Maybe I can make it working.. :-)

**Comment by MarcusWichelmann** [comment]
The main structure for adding documentation-support is now finished, but I cannot make it work somehow. The method `visit_paragraph ()` gets never called and it looks like that the Docklet is not configured to handle documentations... I appreciate any help. ;-)

**Comment by benwaffle** [comment]
#4 has everything in this PR as well as outputting comments

**Pull request closed without merging**
